name: Daily Model Training

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install pandas scikit-learn xgboost lightgbm joblib python-dotenv
          pip install pyarrow==12.0.1 confluent-kafka
          pip install "hopsworks[python]==4.7.*"
      - name: Train & Register Models
        env:
          API_KEY_HS: ${{ secrets.API_KEY_HS }}
        run: python train_openmeteo.py